(async () => {
  'use strict';
  const currentGroup=Math.min(5,Math.max(1,Number(document.body.dataset.group||'1'))),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const workspace=$('#workspace'),imageLayer=$('#image-layer'),canvas=$('#drawing-canvas'),ctx=canvas?.getContext('2d'),uploadInput=$('#image-upload'),drawToggle=$('#draw-toggle'),saveButton=$('#save-workspace'),saveStatus=$('#save-status'),selectedProposalEl=$('#selected-proposal'),clearDrawingButton=$('#clear-drawing'),undoButton=$('#undo-stroke'),documentEditor=$('#document-editor');
  let penColor='#d62828',drawingMode=false,drawing=false,lastPoint=null,strokeSnapshots=[],imageItems=[],dbSdk=null,db=null,loadedDrawingData='',resizeTimer=null;
  const firebaseConfig={apiKey:'AIzaSyCVZqGFfnwb8iesFizm2escpgYVoIQI6Fc',authDomain:'atelier-communication-ambiante.firebaseapp.com',databaseURL:'https://atelier-communication-ambiante-default-rtdb.europe-west1.firebasedatabase.app',projectId:'atelier-communication-ambiante',storageBucket:'atelier-communication-ambiante.firebasestorage.app',messagingSenderId:'43940720482',appId:'1:43940720482:web:c5e6e8776d7f399caf463b'};
  const setSaveStatus=(t,k='')=>{if(saveStatus){saveStatus.textContent=t;saveStatus.className=`save-status ${k}`.trim();}},uid=()=>`img-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;

  const defaultDocumentHtml = documentEditor?.innerHTML || '';
  function sanitizeDocumentHtml(html){
    const template=document.createElement('template');
    template.innerHTML=typeof html==='string'?html:'';
    template.content.querySelectorAll('script,style,iframe,object,embed,svg,math,link,meta,img,video,audio,form,input,button,textarea,select').forEach(el=>el.remove());
    template.content.querySelectorAll('[data-section="budget"]').forEach(el=>el.remove());
    template.content.querySelectorAll('*').forEach(el=>{
      [...el.attributes].forEach(attr=>{
        if(attr.name!=='class'&&attr.name!=='data-section')el.removeAttribute(attr.name);
      });
    });
    return template.innerHTML;
  }
  function insertPlainText(text){
    const sel=window.getSelection();
    if(!sel||!sel.rangeCount)return;
    const range=sel.getRangeAt(0);range.deleteContents();
    const node=document.createTextNode(text);range.insertNode(node);range.setStartAfter(node);range.collapse(true);sel.removeAllRanges();sel.addRange(range);
  }
  documentEditor?.addEventListener('paste',e=>{e.preventDefault();insertPlainText(e.clipboardData?.getData('text/plain')||'');setSaveStatus('Modifications non enregistrées.');});
  documentEditor?.addEventListener('drop',e=>{if(e.dataTransfer?.files?.length)e.preventDefault();});

  function drawDataUrlToCanvas(dataUrl){if(!dataUrl||!ctx||!workspace)return;const img=new Image();img.onload=()=>{const r=workspace.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);ctx.drawImage(img,0,0,r.width,r.height)};img.src=dataUrl}
  function resizeCanvas(preserve=true){if(!workspace||!canvas||!ctx)return;let data=null;if(preserve&&canvas.width&&canvas.height){try{data=canvas.toDataURL('image/png')}catch{}}const r=workspace.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*dpr));canvas.height=Math.max(1,Math.round(r.height*dpr));canvas.style.width=`${r.width}px`;canvas.style.height=`${r.height}px`;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=4;if(data)drawDataUrlToCanvas(data);else if(loadedDrawingData)drawDataUrlToCanvas(loadedDrawingData)}
  const canvasPoint=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(r.width,e.clientX-r.left)),y:Math.max(0,Math.min(r.height,e.clientY-r.top))}};
  function beginStroke(e){if(!drawingMode||!ctx)return;e.preventDefault();if(strokeSnapshots.length>12)strokeSnapshots.shift();try{strokeSnapshots.push(canvas.toDataURL('image/png'))}catch{}drawing=true;lastPoint=canvasPoint(e);canvas.setPointerCapture?.(e.pointerId)}
  function moveStroke(e){if(!drawing||!lastPoint||!ctx)return;e.preventDefault();const p=canvasPoint(e);ctx.strokeStyle=penColor;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(lastPoint.x,lastPoint.y);ctx.lineTo(p.x,p.y);ctx.stroke();lastPoint=p}
  function endStroke(e){if(!drawing)return;drawing=false;lastPoint=null;try{canvas.releasePointerCapture?.(e.pointerId)}catch{}setSaveStatus('Modifications non enregistrées.')}
  function toggleDrawing(force){drawingMode=typeof force==='boolean'?force:!drawingMode;workspace?.classList.toggle('drawing-mode',drawingMode);drawToggle?.classList.toggle('active',drawingMode);drawToggle?.setAttribute('aria-pressed',String(drawingMode));if(drawToggle)drawToggle.textContent=drawingMode?'✎ Dessin actif':'✎ Dessiner'}
  function normalizeRect(i){return{x:Math.max(0,Math.min(92,Number(i.x)||10)),y:Math.max(0,Math.min(92,Number(i.y)||10)),w:Math.max(12,Math.min(70,Number(i.w)||35)),h:Math.max(7,Math.min(60,Number(i.h)||24))}}
  function renderImages(){if(!imageLayer)return;imageLayer.innerHTML='';imageItems.forEach(createImageElement)}
  function createImageElement(item){if(!imageLayer||!workspace)return;Object.assign(item,normalizeRect(item));const box=document.createElement('div');box.className='workspace-image';box.dataset.id=item.id;box.style.left=`${item.x}%`;box.style.top=`${item.y}%`;box.style.width=`${item.w}%`;box.style.height=`${item.h}%`;const img=document.createElement('img');img.src=item.src;img.alt='Image ajoutée au document';box.appendChild(img);const hint=document.createElement('span');hint.className='drag-hint';hint.textContent='Déplacer';box.appendChild(hint);const del=document.createElement('button');del.type='button';del.className='delete-image';del.textContent='×';del.title='Supprimer cette image';del.onclick=e=>{e.stopPropagation();imageItems=imageItems.filter(x=>x.id!==item.id);box.remove();setSaveStatus('Modifications non enregistrées.')};box.appendChild(del);const handle=document.createElement('div');handle.className='resize-handle';handle.title='Redimensionner';box.appendChild(handle);makeDraggable(box,item,handle);imageLayer.appendChild(box)}
  function makeDraggable(box,item,handle){let mode='',start=null,startRect=null;const onMove=e=>{if(!mode||!start||!workspace)return;e.preventDefault();const wr=workspace.getBoundingClientRect(),dx=((e.clientX-start.x)/wr.width)*100,dy=((e.clientY-start.y)/wr.height)*100;if(mode==='drag'){item.x=Math.max(0,Math.min(100-item.w,startRect.x+dx));item.y=Math.max(0,Math.min(100-item.h,startRect.y+dy))}else{item.w=Math.max(12,Math.min(80,startRect.w+dx));item.h=Math.max(7,Math.min(70,startRect.h+dy));item.x=Math.min(item.x,100-item.w);item.y=Math.min(item.y,100-item.h)}box.style.left=`${item.x}%`;box.style.top=`${item.y}%`;box.style.width=`${item.w}%`;box.style.height=`${item.h}%`};const onUp=()=>{if(!mode)return;mode='';start=null;startRect=null;window.removeEventListener('pointermove',onMove);setSaveStatus('Modifications non enregistrées.')};box.addEventListener('pointerdown',e=>{if(drawingMode||e.target.closest('.delete-image')||e.target===handle)return;mode='drag';start={x:e.clientX,y:e.clientY};startRect={x:item.x,y:item.y,w:item.w,h:item.h};window.addEventListener('pointermove',onMove,{passive:false});window.addEventListener('pointerup',onUp,{once:true})});handle.addEventListener('pointerdown',e=>{if(drawingMode)return;e.stopPropagation();mode='resize';start={x:e.clientX,y:e.clientY};startRect={x:item.x,y:item.y,w:item.w,h:item.h};window.addEventListener('pointermove',onMove,{passive:false});window.addEventListener('pointerup',onUp,{once:true})})}
  async function compressImage(file){const dataUrl=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)}),img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=dataUrl}),maxSide=1400,scale=Math.min(1,maxSide/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);return c.toDataURL('image/jpeg',.84)}
  async function addFiles(files){if(!files?.length)return;toggleDrawing(false);const remaining=Math.max(0,6-imageItems.length);if(!remaining){setSaveStatus('Maximum de 6 images atteint.','error');uploadInput.value='';return}for(const file of [...files].slice(0,remaining)){if(!file.type.startsWith('image/'))continue;try{const src=await compressImage(file),n=imageItems.length%5;imageItems.push({id:uid(),src,x:12+n*4,y:10+n*5,w:34,h:24})}catch(e){console.error(e);setSaveStatus('Une image n’a pas pu être importée.','error')}}renderImages();setSaveStatus('Modifications non enregistrées.');uploadInput.value=''}

  function populateLegacy(data){
    if(!documentEditor)return;
    documentEditor.innerHTML=defaultDocumentHtml;
    const values={what:data.text?.what||'',how:data.text?.how||'',where:data.text?.where||''};
    let used=false;
    Object.entries(values).forEach(([key,value])=>{if(!value)return;const slot=documentEditor.querySelector(`[data-section="${key}"] .answer-space`);if(slot){slot.textContent=value;used=true;}});
    if(!used&&data.text?.free){
      const first=documentEditor.querySelector('[data-section="what"] .answer-space');
      if(first)first.textContent=data.text.free;
    }
  }

  async function saveWorkspace(){if(!dbSdk||!db||!canvas||!documentEditor)return;saveButton.disabled=true;setSaveStatus('Enregistrement…');try{const cleanHtml=sanitizeDocumentHtml(documentEditor.innerHTML);const payload={text:{documentHtml:cleanHtml,documentText:(documentEditor.innerText||'').replace(/\u00a0/g,' ').trim()},images:imageItems,drawing:canvas.toDataURL('image/png'),updatedAt:Date.now()};await dbSdk.set(dbSdk.ref(db,`atelier/phase3/groupe${currentGroup}/workspace`),payload);setSaveStatus('Enregistré.','ok')}catch(e){console.error(e);setSaveStatus('Échec de l’enregistrement.','error')}finally{saveButton.disabled=false}}
  async function loadWorkspace(){const snap=await dbSdk.get(dbSdk.ref(db,`atelier/phase3/groupe${currentGroup}/workspace`)),data=snap.val()||{};if(documentEditor){if(data.text?.documentHtml)documentEditor.innerHTML=sanitizeDocumentHtml(data.text.documentHtml);else populateLegacy(data)}imageItems=Array.isArray(data.images)?data.images.filter(Boolean):(data.images?Object.values(data.images):[]);imageItems=imageItems.filter(x=>x&&x.src&&x.id);loadedDrawingData=typeof data.drawing==='string'?data.drawing:'';renderImages();resizeCanvas(false);if(loadedDrawingData)drawDataUrlToCanvas(loadedDrawingData);setSaveStatus('Travail chargé.','ok')}
  async function loadSelectedProposal(){try{const cs=await dbSdk.get(dbSdk.ref(db,`atelier/phase2/choix/groupe${currentGroup}`)),choice=cs.val();if(!choice?.proposalId||!choice?.sourceGroup||!choice?.slot){selectedProposalEl.className='selected-proposal empty';selectedProposalEl.textContent='Aucune modification prioritaire n’a encore été retenue pour ce groupe en Phase 2.';return}const ps=await dbSdk.get(dbSdk.ref(db,`atelier/phase1/groupe${choice.sourceGroup}/propositions/${choice.slot}`)),text=ps.val();selectedProposalEl.className='selected-proposal';selectedProposalEl.innerHTML='';const source=document.createElement('span');source.className='proposal-source';source.textContent=`Proposition du Groupe ${choice.sourceGroup} · Modification ${choice.slot}`;const content=document.createElement('div');content.textContent=typeof text==='string'&&text.trim()?text:'La proposition retenue n’est plus renseignée en Phase 1.';selectedProposalEl.append(source,content)}catch(e){console.error(e);selectedProposalEl.className='selected-proposal empty';selectedProposalEl.textContent='Impossible de charger la modification retenue.'}}
  drawToggle?.addEventListener('click',()=>toggleDrawing());uploadInput?.addEventListener('change',e=>addFiles(e.target.files));saveButton?.addEventListener('click',saveWorkspace);$$('.pen-color').forEach(b=>b.addEventListener('click',()=>{penColor=b.dataset.color||penColor;$$('.pen-color').forEach(x=>x.classList.toggle('active',x===b));toggleDrawing(true)}));clearDrawingButton?.addEventListener('click',()=>{if(!ctx||!workspace)return;const r=workspace.getBoundingClientRect();if(strokeSnapshots.length>12)strokeSnapshots.shift();try{strokeSnapshots.push(canvas.toDataURL('image/png'))}catch{}ctx.clearRect(0,0,r.width,r.height);loadedDrawingData='';setSaveStatus('Modifications non enregistrées.')});undoButton?.addEventListener('click',()=>{const prev=strokeSnapshots.pop();if(!prev||!ctx||!workspace)return;const r=workspace.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);drawDataUrlToCanvas(prev);setSaveStatus('Modifications non enregistrées.')});canvas?.addEventListener('pointerdown',beginStroke);canvas?.addEventListener('pointermove',moveStroke);canvas?.addEventListener('pointerup',endStroke);canvas?.addEventListener('pointercancel',endStroke);documentEditor?.addEventListener('input',()=>setSaveStatus('Modifications non enregistrées.'));window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>resizeCanvas(true),180)});
  try{const [appSdk,authSdk,databaseSdk]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js')]);dbSdk=databaseSdk;const app=appSdk.initializeApp(firebaseConfig),auth=authSdk.getAuth(app);await authSdk.signInAnonymously(auth);db=dbSdk.getDatabase(app);resizeCanvas(false);await Promise.all([loadSelectedProposal(),loadWorkspace()])}catch(e){console.error(e);setSaveStatus('Connexion Firebase impossible.','error');selectedProposalEl.className='selected-proposal empty';selectedProposalEl.textContent='Connexion à la base impossible.'}
})();
